version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/repo
    branches:
      only:
        - dev
        - staging
        - master
        - features/*
    steps:
      - checkout
      - run:
          name: Installing NPM Dependencies
          command: npm install

  deploy-dev:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: echo "Deploy in dev"
  deploy-prod:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: echo "Deploy in prod"
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master